# Generated by Django 4.2.4 on 2023-08-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qrcode_model',
        ),
    ]
